use gpui::*;

const MAIN_MENU_LIST_STUDIES_STORY_ID: &str = "main-menu-raycast-weight-studies";
const MAIN_MENU_LIST_STUDIES_ENV: &str = "SCRIPT_KIT_STORYBOOK_MAIN_MENU_LIST_STUDY";

#[derive(Clone, Copy, Debug, PartialEq)]
struct MainMenuListStudySpec {
    id: &'static str,
    name: &'static str,
    description: &'static str,
    row_height: f32,
    icon_size: f32,
    content_gap: f32,
    title_size: f32,
    subtitle_size: f32,
    section_size: f32,
    title_line_height: f32,
    subtitle_line_height: f32,
    title_weight: FontWeight,
    selected_title_weight: FontWeight,
    subtitle_weight: FontWeight,
    section_weight: FontWeight,
    list_top_padding: f32,
    selected_fill_opacity: f32,
    subtitle_opacity: f32,
}

const SPECS: [MainMenuListStudySpec; 21] = [
    MainMenuListStudySpec {
        id: "all-normal-baseline",
        name: "[01] All Normal Baseline",
        description: "The anchor variation: larger all-normal typography inside the exact main-menu chrome.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "tighter-rows",
        name: "[02] Tighter Rows",
        description: "A slightly denser version of the baseline with tighter row height and line rhythm.",
        row_height: 52.0,
        icon_size: 17.0,
        content_gap: 9.0,
        title_size: 18.2,
        subtitle_size: 14.2,
        section_size: 12.8,
        title_line_height: 22.0,
        subtitle_line_height: 17.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.09,
        subtitle_opacity: 0.54,
    },
    MainMenuListStudySpec {
        id: "roomier-rows",
        name: "[03] Roomier Rows",
        description: "A roomier take with more height and breathing room in the copy.",
        row_height: 56.0,
        icon_size: 18.0,
        content_gap: 10.5,
        title_size: 18.8,
        subtitle_size: 14.8,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.5,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 6.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.58,
    },
    MainMenuListStudySpec {
        id: "smaller-title",
        name: "[04] Smaller Title",
        description: "The title pulls back a little so the list feels calmer and flatter.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 17.8,
        subtitle_size: 14.4,
        section_size: 13.0,
        title_line_height: 22.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.58,
    },
    MainMenuListStudySpec {
        id: "larger-title",
        name: "[05] Larger Title",
        description: "The title gets a bit more authority while the rest of the row stays stable.",
        row_height: 55.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 19.4,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 24.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "quieter-subtitle",
        name: "[06] Quieter Subtitle",
        description: "Secondary copy recedes noticeably so the primary title does more of the work.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.1,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 17.5,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.46,
    },
    MainMenuListStudySpec {
        id: "stronger-subtitle",
        name: "[07] Stronger Subtitle",
        description: "Descriptions come forward and start participating in the scan path.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.5,
        subtitle_size: 15.2,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.5,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::MEDIUM,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.66,
    },
    MainMenuListStudySpec {
        id: "smaller-sections",
        name: "[08] Smaller Sections",
        description: "Section labels whisper more aggressively above the larger rows.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 12.4,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "larger-sections",
        name: "[09] Larger Sections",
        description: "Section labels become more legible while staying visually subordinate to rows.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.6,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::MEDIUM,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "tighter-icon-gap",
        name: "[10] Tighter Icon Gap",
        description: "The icon block tucks in closer to the text for a denser rhythm.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 8.5,
        title_size: 18.6,
        subtitle_size: 14.5,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "roomier-icon-gap",
        name: "[11] Roomier Icon Gap",
        description: "A wider icon-to-text gap makes the row structure feel more deliberate.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 12.0,
        title_size: 18.4,
        subtitle_size: 14.4,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "softer-selection",
        name: "[12] Softer Selection",
        description: "The background fill steps back so the accent bar becomes the dominant focus signal.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.07,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "stronger-selection",
        name: "[13] Stronger Selection",
        description: "A fuller rectangular selection background gives the focused row more mass.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.14,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "selected-semibold",
        name: "[14] Selected Semibold",
        description: "Only the selected title gets appreciably heavier, preserving a quiet baseline elsewhere.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::SEMIBOLD,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "bigger-icons",
        name: "[15] Bigger Icons",
        description: "A larger icon treatment shifts a little more weight to the leading edge.",
        row_height: 55.0,
        icon_size: 19.5,
        content_gap: 10.0,
        title_size: 18.4,
        subtitle_size: 14.4,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "smaller-icons",
        name: "[16] Smaller Icons",
        description: "Leading icons step back so type carries more of the rhythm.",
        row_height: 53.0,
        icon_size: 16.5,
        content_gap: 9.5,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "tighter-list-top",
        name: "[17] Tighter List Top",
        description: "The first section begins sooner below the divider, giving the list a more immediate start.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 2.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "roomier-list-top",
        name: "[18] Roomier List Top",
        description: "More space above the first section creates a slower, more deliberate opening rhythm.",
        row_height: 54.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 18.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 8.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "compressed-subtitle-lh",
        name: "[19] Compressed Subtitle",
        description: "Subtitle line-height compresses a little to make the rows feel denser without shrinking the font.",
        row_height: 53.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 17.0,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "airier-subtitle-lh",
        name: "[20] Airier Subtitle",
        description: "Subtitle lines get a little more air, softening the list without changing the structure.",
        row_height: 55.0,
        icon_size: 18.0,
        content_gap: 10.0,
        title_size: 18.6,
        subtitle_size: 14.6,
        section_size: 13.0,
        title_line_height: 23.0,
        subtitle_line_height: 19.5,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::NORMAL,
        list_top_padding: 4.0,
        selected_fill_opacity: 0.10,
        subtitle_opacity: 0.56,
    },
    MainMenuListStudySpec {
        id: "balanced-alt",
        name: "[21] Balanced Alt",
        description: "A final calibrated pass that keeps the all-normal scale but balances row height, subtitle presence, and spacing differently.",
        row_height: 55.0,
        icon_size: 18.0,
        content_gap: 10.5,
        title_size: 18.9,
        subtitle_size: 14.7,
        section_size: 13.2,
        title_line_height: 23.5,
        subtitle_line_height: 18.2,
        title_weight: FontWeight::NORMAL,
        selected_title_weight: FontWeight::MEDIUM,
        subtitle_weight: FontWeight::NORMAL,
        section_weight: FontWeight::MEDIUM,
        list_top_padding: 5.0,
        selected_fill_opacity: 0.11,
        subtitle_opacity: 0.60,
    },
];

fn spec_to_list_item_metrics(
    spec: MainMenuListStudySpec,
) -> crate::list_item::ListItemMetricsOverride {
    let section_padding_top = (8.0 + spec.list_top_padding).max(8.0);
    let section_header_height = (section_padding_top + spec.section_size + 10.0).max(28.0);

    crate::list_item::ListItemMetricsOverride {
        item_height: spec.row_height,
        section_header_height,
        section_padding_top,
        icon_container_size: (spec.icon_size + 2.0).max(spec.icon_size),
        icon_svg_size: spec.icon_size,
        icon_text_gap: spec.content_gap,
        name_font_size: spec.title_size,
        name_line_height: spec.title_line_height,
        desc_font_size: spec.subtitle_size,
        desc_line_height: spec.subtitle_line_height,
        section_header_font_size: spec.section_size,
        section_gap: 6.0,
        name_weight: spec.title_weight,
        selected_name_weight: spec.selected_title_weight,
        desc_weight: spec.subtitle_weight,
        section_weight: spec.section_weight,
        desc_quiet_alpha: (spec.subtitle_opacity.clamp(0.0, 1.0) * 255.0).round() as u32,
    }
}

#[cfg(feature = "storybook")]
pub fn adopted_main_menu_list_study_metrics() -> Option<crate::list_item::ListItemMetricsOverride> {
    if std::env::var_os(MAIN_MENU_LIST_STUDIES_ENV).is_none() {
        return None;
    }

    let selected = super::load_selected_story_variant(MAIN_MENU_LIST_STUDIES_STORY_ID)?;
    let spec = resolve_spec(&selected)?;
    Some(spec_to_list_item_metrics(spec))
}

fn resolve_spec(stable_id: &str) -> Option<MainMenuListStudySpec> {
    SPECS.iter().copied().find(|spec| spec.id == stable_id)
}
