        let preview_panel = div()
            .w_1_2()
            .h_full()
            .border_l_1()
            .border_color(border_rgba)
            .px(px(design_spacing.padding_lg))
            .py(px(design_spacing.padding_md))
            .flex()
            .flex_col()
            .gap(px(10.0))
            .overflow_y_hidden()
            // ── Customize section ──────────────────────────────────
            .child(
                div()
                    .text_xs()
                    .text_color(rgb(text_dimmed))
                    .font_weight(gpui::FontWeight::SEMIBOLD)
                    .child("CUSTOMIZE"),
            )
            // Accent color row (with name)
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .items_center()
                            .gap(px(6.0))
                            .child(
                                div()
                                    .text_xs()
                                    .text_color(rgb(text_muted))
                                    .child("Accent Color"),
                            )
                            .child(
                                div()
                                    .text_xs()
                                    .text_color(rgb(accent_color))
                                    .font_weight(gpui::FontWeight::SEMIBOLD)
                                    .child(accent_name.to_string()),
                            ),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .gap(px(4.0))
                            .flex_wrap()
                            .children(accent_swatches),
                    ),
            )
            // Opacity row (10 steps)
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_muted))
                            .child(format!(
                                "Window Opacity  {:.0}%",
                                current_opacity_main * 100.0
                            )),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .gap(px(2.0))
                            .flex_wrap()
                            .children(opacity_buttons),
                    ),
            )
            // Vibrancy toggle + material row
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_muted))
                            .child("Vibrancy Blur"),
                    )
                    .child(vibrancy_toggle)
                    .when(vibrancy_enabled, |d| {
                        d.child(
                            div()
                                .flex()
                                .flex_col()
                                .gap(px(4.0))
                                .mt(px(4.0))
                                .child(
                                    div()
                                        .text_xs()
                                        .text_color(rgb(text_muted))
                                        .child("Material"),
                                )
                                .child(
                                    div()
                                        .flex()
                                        .flex_row()
                                        .gap(px(3.0))
                                        .flex_wrap()
                                        .children(material_buttons),
                                ),
                        )
                    }),
            )
            // Font size row
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_muted))
                            .child(format!("UI Font Size  {:.0}px", current_ui_font_size)),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .gap(px(4.0))
                            .children(font_size_buttons),
                    ),
            )
            // Reset button
            .child(reset_button)
            // ── Preview section ────────────────────────────────────
            .child(
                div()
                    .w_full()
                    .mt(px(4.0))
                    .pt(px(8.0))
                    .border_t_1()
                    .border_color(border_rgba)
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_dimmed))
                            .font_weight(gpui::FontWeight::SEMIBOLD)
                            .child("PREVIEW"),
                    ),
            )
            // Mock search box
            .child(
                div()
                    .w_full()
                    .h(px(28.0))
                    .rounded(px(6.0))
                    .bg(rgb(bg_search_box))
                    .border_1()
                    .border_color(border_rgba)
                    .px(px(10.0))
                    .flex()
                    .flex_row()
                    .items_center()
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_muted))
                            .child("Search scripts..."),
                    ),
            )
            // Mock list items
            .child(
                div()
                    .w_full()
                    .rounded(px(6.0))
                    .border_1()
                    .border_color(border_rgba)
                    .overflow_hidden()
                    .flex()
                    .flex_col()
                    .child(
                        div()
                            .w_full()
                            .h(px(28.0))
                            .bg(rgb(accent_color))
                            .px(px(10.0))
                            .flex()
                            .flex_row()
                            .items_center()
                            .child(
                                div()
                                    .text_xs()
                                    .font_weight(gpui::FontWeight::SEMIBOLD)
                                    .text_color(rgb(text_on_accent))
                                    .child("Selected Item"),
                            ),
                    )
                    .child(
                        div()
                            .w_full()
                            .h(px(28.0))
                            .bg(rgb(bg_main))
                            .px(px(10.0))
                            .flex()
                            .flex_row()
                            .items_center()
                            .child(
                                div()
                                    .text_xs()
                                    .text_color(rgb(text_primary))
                                    .child("Regular Item"),
                            ),
                    )
                    .child(
                        div()
                            .w_full()
                            .h(px(28.0))
                            .bg(rgb(bg_main))
                            .px(px(10.0))
                            .flex()
                            .flex_row()
                            .items_center()
                            .child(
                                div()
                                    .text_xs()
                                    .text_color(rgb(text_secondary))
                                    .child("Another Item"),
                            ),
                    ),
            )
            // Terminal + semantic colors
            .child(
                div()
                    .flex()
                    .flex_col()
                    .gap(px(4.0))
                    .child(
                        div()
                            .text_xs()
                            .text_color(rgb(text_dimmed))
                            .font_weight(gpui::FontWeight::SEMIBOLD)
                            .child("TERMINAL"),
                    )
                    .child(
                        div().flex().flex_row().gap(px(2.0)).children(
                            term_colors
                                .iter()
                                .map(|&c| div().w(px(16.0)).h(px(12.0)).rounded(px(2.0)).bg(rgb(c))),
                        ),
                    )
                    .child(
                        div().flex().flex_row().gap(px(2.0)).children(
                            term_bright
                                .iter()
                                .map(|&c| div().w(px(16.0)).h(px(12.0)).rounded(px(2.0)).bg(rgb(c))),
                        ),
                    ),
            )
            // Semantic colors
            .child(
                div()
                    .flex()
                    .flex_row()
                    .gap(px(8.0))
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .items_center()
                            .gap(px(3.0))
                            .child(div().w(px(7.0)).h(px(7.0)).rounded(px(4.0)).bg(rgb(ui_success)))
                            .child(div().text_xs().text_color(rgb(ui_success)).child("OK")),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .items_center()
                            .gap(px(3.0))
                            .child(div().w(px(7.0)).h(px(7.0)).rounded(px(4.0)).bg(rgb(ui_error)))
                            .child(div().text_xs().text_color(rgb(ui_error)).child("Err")),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .items_center()
                            .gap(px(3.0))
                            .child(div().w(px(7.0)).h(px(7.0)).rounded(px(4.0)).bg(rgb(ui_warning)))
                            .child(div().text_xs().text_color(rgb(ui_warning)).child("Warn")),
                    )
                    .child(
                        div()
                            .flex()
                            .flex_row()
                            .items_center()
                            .gap(px(3.0))
                            .child(div().w(px(7.0)).h(px(7.0)).rounded(px(4.0)).bg(rgb(ui_info)))
                            .child(div().text_xs().text_color(rgb(ui_info)).child("Info")),
                    ),
            );
