//! Clipboard secret rejection (hard rules)
//!
//! Pure rejection logic for password-manager sources, concealed pasteboard types,
//! and conservative secret-content patterns. Rejected clipboard payloads are never
//! stored — not even in unpinned history.

use regex::Regex;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{OnceLock, RwLock};
use tracing::info;

/// Why a clipboard capture was rejected. Never log clipboard content alongside this.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RejectionReason {
    ConcealedPasteboardType,
    BlockedSourceApp,
    SecretContentPattern,
}

/// User-configurable extensions to the built-in rejection rules.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SecretRejectionConfig {
    pub extra_blocked_source_apps: Vec<String>,
    pub extra_secret_patterns: Vec<String>,
}

/// Default password-manager / keychain bundle ID prefixes (prefix match).
pub const DEFAULT_BLOCKED_SOURCE_APPS: &[&str] = &[
    "com.1password.1password",
    "com.agilebits.onepassword7",
    "com.bitwarden.desktop",
    "org.keepassxc.keepassxc",
    "com.apple.Passwords",
    "com.apple.keychainaccess",
];

/// Conservative default regex patterns — false negatives acceptable, prose false positives are not.
pub const DEFAULT_SECRET_PATTERNS: &[&str] = &[
    // AWS access key IDs
    r"(?m)\bAKIA[0-9A-Z]{16}\b",
    // GitHub personal/oauth tokens
    r"(?m)\bgh[po]_[A-Za-z0-9_]{20,}\b",
    // PEM private key headers
    r"(?m)-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----",
    // JWT shape (three base64url segments)
    r"(?m)\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b",
];

const CONCEALED_PASTEBOARD_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

static REJECTION_COUNT: AtomicU64 = AtomicU64::new(0);
static EXTRA_BLOCKED_SOURCE_APPS: OnceLock<RwLock<Vec<String>>> = OnceLock::new();
static COMPILED_SECRET_PATTERNS: OnceLock<RwLock<Vec<Regex>>> = OnceLock::new();

fn extra_blocked_apps() -> &'static RwLock<Vec<String>> {
    EXTRA_BLOCKED_SOURCE_APPS.get_or_init(|| RwLock::new(Vec::new()))
}

fn compiled_secret_patterns() -> &'static RwLock<Vec<Regex>> {
    COMPILED_SECRET_PATTERNS.get_or_init(|| {
        let patterns = compile_patterns(DEFAULT_SECRET_PATTERNS, &[]);
        RwLock::new(patterns)
    })
}

fn compile_patterns(defaults: &[&str], extras: &[String]) -> Vec<Regex> {
    let mut compiled = Vec::new();
    for pattern in defaults {
        push_compiled_pattern(&mut compiled, pattern);
    }
    for pattern in extras {
        push_compiled_pattern(&mut compiled, pattern.as_str());
    }
    compiled
}

fn push_compiled_pattern(compiled: &mut Vec<Regex>, pattern: &str) {
    match Regex::new(pattern) {
        Ok(regex) => compiled.push(regex),
        Err(error) => {
            tracing::warn!(
                error = %error,
                "Skipping invalid clipboard secret rejection regex pattern"
            );
        }
    }
}

/// Load user extensions from config (call before `init_clipboard_history`).
pub fn configure_secret_rejection(config: SecretRejectionConfig) {
    if let Ok(mut guard) = extra_blocked_apps().write() {
        *guard = config.extra_blocked_source_apps;
    }

    let patterns = compile_patterns(DEFAULT_SECRET_PATTERNS, &config.extra_secret_patterns);
    if let Ok(mut guard) = compiled_secret_patterns().write() {
        *guard = patterns;
    }
}

/// Total rejections since process start (inspectable counter).
pub fn rejection_count() -> u64 {
    REJECTION_COUNT.load(Ordering::Relaxed)
}

/// Record a rejection and emit a log line without clipboard content.
pub fn record_rejection(reason: RejectionReason) {
    let total = REJECTION_COUNT.fetch_add(1, Ordering::Relaxed) + 1;
    info!(
        reason = ?reason,
        rejection_count = total,
        "clipboard_secret_rejection"
    );
}

/// macOS NSPasteboard concealed/auto-generated marker types. Non-macOS: always false.
#[cfg(target_os = "macos")]
pub fn pasteboard_has_concealed_types() -> bool {
    use cocoa::appkit::NSPasteboard;
    use cocoa::base::{id, nil};
    use objc::{msg_send, sel, sel_impl};

    // SAFETY: NSPasteboard pointers and Foundation collections are nil-checked.
    unsafe {
        let pasteboard: id = NSPasteboard::generalPasteboard(nil);
        if pasteboard == nil {
            return false;
        }

        if pasteboard_declares_concealed_type(pasteboard) {
            return true;
        }

        let items: id = msg_send![pasteboard, pasteboardItems];
        if items == nil {
            return false;
        }

        let item_count: usize = msg_send![items, count];
        for item_index in 0..item_count {
            let item: id = msg_send![items, objectAtIndex: item_index];
            if item == nil {
                continue;
            }
            let types: id = msg_send![item, types];
            if types == nil {
                continue;
            }
            if collection_contains_concealed_type(types) {
                return true;
            }
        }

        false
    }
}

#[cfg(not(target_os = "macos"))]
pub fn pasteboard_has_concealed_types() -> bool {
    false
}

#[cfg(target_os = "macos")]
unsafe fn pasteboard_declares_concealed_type(pasteboard: cocoa::base::id) -> bool {
    use objc::{msg_send, sel, sel_impl};

    let types: cocoa::base::id = msg_send![pasteboard, types];
    if types.is_null() {
        return false;
    }
    collection_contains_concealed_type(types)
}

#[cfg(target_os = "macos")]
unsafe fn collection_contains_concealed_type(types: cocoa::base::id) -> bool {
    use objc::{msg_send, sel, sel_impl};

    let type_count: usize = msg_send![types, count];
    for type_index in 0..type_count {
        let type_id: cocoa::base::id = msg_send![types, objectAtIndex: type_index];
        if type_id.is_null() {
            continue;
        }
        if let Some(type_name) = nsstring_to_string(type_id) {
            if CONCEALED_PASTEBOARD_TYPES
                .iter()
                .any(|concealed| type_name == *concealed)
            {
                return true;
            }
        }
    }
    false
}

#[cfg(target_os = "macos")]
unsafe fn nsstring_to_string(value: cocoa::base::id) -> Option<String> {
    use objc::{msg_send, sel, sel_impl};

    if value.is_null() {
        return None;
    }
    let utf8: *const std::os::raw::c_char = msg_send![value, UTF8String];
    if utf8.is_null() {
        return None;
    }
    std::ffi::CStr::from_ptr(utf8)
        .to_str()
        .ok()
        .map(str::to_string)
}

/// Rule 2 — blocked source app (prefix match on bundle ID).
pub fn matches_blocked_source_app(bundle_id: &str) -> bool {
    if DEFAULT_BLOCKED_SOURCE_APPS
        .iter()
        .any(|blocked| bundle_id.starts_with(blocked))
    {
        return true;
    }

    extra_blocked_bundle_ids()
        .iter()
        .any(|blocked| bundle_id.starts_with(blocked))
}

fn extra_blocked_bundle_ids() -> Vec<String> {
    extra_blocked_apps()
        .read()
        .map(|guard| guard.clone())
        .unwrap_or_default()
}

/// Rule 3 — secret content pattern match.
pub fn matches_secret_content(text: &str) -> bool {
    compiled_secret_patterns()
        .read()
        .map(|patterns| patterns.iter().any(|pattern| pattern.is_match(text)))
        .unwrap_or(false)
}

/// Pre-payload rejection probe (concealed types + source app).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ClipboardPreCaptureProbe {
    pub pasteboard_has_concealed_types: bool,
}

impl ClipboardPreCaptureProbe {
    pub fn live() -> Self {
        Self {
            pasteboard_has_concealed_types: pasteboard_has_concealed_types(),
        }
    }
}

pub fn reject_before_reading_payload(
    source_bundle_id: Option<&str>,
    probe: ClipboardPreCaptureProbe,
) -> Option<RejectionReason> {
    if probe.pasteboard_has_concealed_types {
        return Some(RejectionReason::ConcealedPasteboardType);
    }

    if source_bundle_id.is_some_and(matches_blocked_source_app) {
        return Some(RejectionReason::BlockedSourceApp);
    }

    None
}

pub fn reject_text_content(text: &str) -> Option<RejectionReason> {
    if matches_secret_content(text) {
        Some(RejectionReason::SecretContentPattern)
    } else {
        None
    }
}

pub fn evaluate_text_capture_rejection(
    source_bundle_id: Option<&str>,
    probe: ClipboardPreCaptureProbe,
    text: &str,
) -> Option<RejectionReason> {
    reject_before_reading_payload(source_bundle_id, probe).or_else(|| reject_text_content(text))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_matches_blocked_source_app_defaults() {
        assert!(matches_blocked_source_app("com.1password.1password"));
        assert!(matches_blocked_source_app(
            "com.1password.1password.browser-helper"
        ));
        assert!(matches_blocked_source_app("com.bitwarden.desktop"));
        assert!(matches_blocked_source_app("org.keepassxc.keepassxc"));
        assert!(matches_blocked_source_app("com.apple.Passwords"));
        assert!(matches_blocked_source_app("com.apple.keychainaccess"));
        assert!(!matches_blocked_source_app("com.apple.TextEdit"));
    }

    /// `configure_secret_rejection` mutates process-global state, so all
    /// configure assertions live in ONE test to avoid races between parallel
    /// test threads clobbering each other's extras.
    #[test]
    fn test_configure_secret_rejection_extends_blocklist_and_patterns() {
        configure_secret_rejection(SecretRejectionConfig {
            extra_blocked_source_apps: vec!["com.example.vault".to_string()],
            extra_secret_patterns: vec![r"sk-live-[0-9]{8}".to_string()],
        });
        assert!(matches_blocked_source_app("com.example.vault.helper"));
        assert!(matches_secret_content("sk-live-12345678"));
        assert!(!matches_secret_content("sk-live is a Stripe prefix"));
        // Defaults still apply alongside extras.
        assert!(matches_blocked_source_app("com.bitwarden.desktop"));
        assert!(matches_secret_content("key=AKIAIOSFODNN7EXAMPLE"));
    }

    #[test]
    fn test_matches_secret_content_defaults_without_prose_false_positives() {
        assert!(matches_secret_content("key=AKIAIOSFODNN7EXAMPLE"));
        assert!(matches_secret_content(
            "token ghp_1234567890abcdefghijklmnopqrstuvwxyz"
        ));
        assert!(matches_secret_content(
            "-----BEGIN RSA PRIVATE KEY-----\nMIIE"
        ));
        // Realistic JWT: HS256 signatures are ~43 base64url chars.
        assert!(matches_secret_content(
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        ));

        assert!(!matches_secret_content(
            "Please review the JWT section of the OAuth guide before deploying."
        ));
        assert!(!matches_secret_content(
            "The AKIA prefix is mentioned in AWS docs as an access key shape."
        ));
        assert!(!matches_secret_content("ghp_ is the GitHub token prefix."));
    }

    #[test]
    fn test_reject_before_reading_payload_concealed_flag() {
        let reason = reject_before_reading_payload(
            None,
            ClipboardPreCaptureProbe {
                pasteboard_has_concealed_types: true,
            },
        );
        assert_eq!(reason, Some(RejectionReason::ConcealedPasteboardType));
    }

    #[test]
    fn test_reject_before_reading_payload_blocked_source() {
        let reason = reject_before_reading_payload(
            Some("com.bitwarden.desktop"),
            ClipboardPreCaptureProbe {
                pasteboard_has_concealed_types: false,
            },
        );
        assert_eq!(reason, Some(RejectionReason::BlockedSourceApp));
    }

    #[test]
    fn test_record_rejection_increments_counter() {
        let before = rejection_count();
        record_rejection(RejectionReason::SecretContentPattern);
        assert_eq!(rejection_count(), before + 1);
    }
}
