/**
 * Shared runtime helpers for isolated Codex imp profiles.
 *
 * Self-improvement is owned by lib/self-improve.ts and is available to every
 * imp through this shared runtime. It is opt-in: normal profiles remain a
 * no-op unless `selfImprove.enabled` or CODEX_IMP_SELF_IMPROVE enables them.
 */
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  symlinkSync,
  writeFileSync,
} from "fs";
import { join } from "path";
import type { ImpConfig } from "./isolated.ts";
import {
  applySelfImproveOverlay,
  profileLibDir,
  resolveSelfImprove,
  stopHookEnabled,
  type SelfImproveConfig,
} from "./self-improve.ts";

export type { SelfImproveConfig };

export interface PreparedCodexHome {
  /** Env vars to merge into the spawned Codex process. */
  extraEnv: Record<string, string>;
  hooksEnabled: boolean;
  lessonsPath?: string;
}

export function hooksEnabled(config: ImpConfig): boolean {
  return stopHookEnabled(config);
}

export function applyLessonOverlay(config: ImpConfig): ImpConfig {
  return applySelfImproveOverlay(config);
}

function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function prepareIsolatedCodexHome(
  config: ImpConfig,
  isolatedHome: string,
  realHome = process.env.HOME!,
): PreparedCodexHome {
  mkdirSync(isolatedHome, { recursive: true });

  const authSrc = `${realHome}/.codex/auth.json`;
  const authDst = `${isolatedHome}/auth.json`;
  if (existsSync(authSrc) && !existsSync(authDst)) {
    symlinkSync(authSrc, authDst);
  }

  const resolved = resolveSelfImprove(config);
  if (!resolved.enabled) {
    return { extraEnv: {}, hooksEnabled: false };
  }

  const extraEnv = { ...resolved.extraEnv };
  if (!resolved.stopHook) {
    return { extraEnv, hooksEnabled: false, lessonsPath: resolved.lessonsPath };
  }

  const hooksDir = join(isolatedHome, "hooks");
  mkdirSync(hooksDir, { recursive: true });
  const handlerSrc = join(profileLibDir(resolved.selfPath), "self-improve-stop.ts");
  const handlerDst = join(hooksDir, "self-improve-stop.ts");
  copyFileSync(handlerSrc, handlerDst);
  chmodSync(handlerDst, 0o755);

  writeFileSync(
    join(isolatedHome, "config.toml"),
    ["# Generated by codex-imps for this self-improving profile.", "bypass_hook_trust = true", "", "[features]", "hooks = true", ""].join("\n"),
    "utf8",
  );

  writeFileSync(
    join(isolatedHome, "hooks.json"),
    JSON.stringify(
      {
        hooks: {
          Stop: [
            {
              hooks: [
                {
                  type: "command",
                  command: `bun ${shellQuote(handlerDst)}`,
                  timeout: 10,
                  statusMessage: "self-improve: scan turn for failures",
                },
              ],
            },
          ],
        },
      },
      null,
      2,
    ) + "\n",
    "utf8",
  );

  return { extraEnv, hooksEnabled: true, lessonsPath: resolved.lessonsPath };
}
