#!/usr/bin/env bun

const classifications = [
  "ok",
  "reproduced",
  "fixed",
  "not-reproduced",
  "blocked-by-missing-primitive",
  "blocked-by-target-ambiguity",
  "blocked-by-stale-generation",
  "blocked-by-unsafe-operation",
  "blocked-by-permission",
  "blocked-by-real-data-risk",
  "blocked-by-native-escalation-required",
  "blocked-by-fixture-only",
  "blocked-by-timeout",
  "blocked-by-response-timeout",
  "blocked-by-external-wrapper-timeout",
  "blocked-by-session-queue",
  "blocked-by-parse-error",
  // Session transport died or was never started (session_dead, forwarder_dead,
  // no_session, app_process_dead_*): retry a dimension CLI cannot help; the
  // caller must restart the session. Emitted by lib/client.ts classification.
  "blocked-by-session-lifecycle",
  // surface.ts / investigate.ts: the requested SurfaceKind has no entry in
  // docs/ai/contracts/surface-contracts.json.
  "blocked-by-unknown-surface",
  // investigate.ts progress states: the investigation loop has not yet
  // produced (needs-red-proof) or has produced (ready-for-green-proof) a
  // failing red receipt for the story under investigation.
  "needs-red-proof",
  "ready-for-green-proof",
];

const receiptEnvelopeFields = [
  "schemaVersion",
  "tool",
  "command",
  "invocationId",
  "sessionId",
  "repo",
  "startedAt",
  "endedAt",
  "durationMs",
  "target",
  "preconditions",
  "result",
  "assertions",
  "classification",
  "warnings",
  "errors",
  "redaction",
];

const targetIdentityFields = [
  "requestedTarget.selector",
  "requestedTarget.strict",
  "resolvedTarget.automationId",
  "resolvedTarget.stableTargetId",
  "resolvedTarget.nativeWindowId",
  "resolvedTarget.axWindowId",
  "resolvedTarget.pid",
  "resolvedTarget.targetKind",
  "resolvedTarget.hostKind",
  "resolvedTarget.parentAutomationId",
  "resolvedTarget.openerAutomationId",
  "resolvedTarget.surfaceKind",
  "resolvedTarget.appViewVariant",
  "resolvedTarget.nativeFooterSurface",
  "resolvedTarget.surfaceFamily",
  "resolvedTarget.routeId",
  "resolvedTarget.routeStack",
  "resolvedTarget.targetGeneration",
  "resolvedTarget.surfaceGeneration",
  "resolvedTarget.dataGeneration",
  "resolvedTarget.bounds",
  "resolvedTarget.screenId",
  "resolvedTarget.zOrder",
  "resolvedTarget.visible",
  "resolvedTarget.frontmost",
  "resolvedTarget.focused",
  "resolvedTarget.screenshotIdentity",
  "resolvedTarget.strictTargetMatch",
  "resolvedTarget.strictTargetMismatch",
  "resolvedTarget.strictTargetMismatch.expectedSurfaceKind",
  "resolvedTarget.strictTargetMismatch.actualCandidates",
  "resolvedTarget.strictTargetMismatch.mismatchReason",
  "resolvedTarget.ambiguity",
];

const primitiveSchemas = [
  {
    primitive: "devtools.inspect.orchestrate",
    requiredResultFields: [
      "bug.text",
      "bug.suspectedSurface",
      "requestedTarget",
      "resolvedTarget.automationId",
      "resolvedTarget.targetKind",
      "visibleWindowProof.screenshotIdentity",
      "primitiveStack[].name",
      "primitiveStack[].classification",
      "capabilityDetails",
      "missingFieldDetails",
      "recommendedNextPrimitives",
      "likelyOwners",
      "doNotUseRecipeReason",
      "cleanup.statusCommand",
    ],
    failClosedWhen: [
      "strict target identity is unavailable",
      "required state/elements/layout/screenshot primitive is blocked",
      "a missing primitive is needed for the bug report",
    ],
    implementation: "bun scripts/devtools/inspect.ts --bug <report> --surface <SurfaceKind>",
  },
  {
    primitive: "devtools.targets.inspect",
    requiredResultFields: targetIdentityFields,
    failClosedWhen: ["strictTargetMatch is false", "target is hidden for visual proof", "targetGeneration changes during measurement"],
  },
  {
    primitive: "devtools.surface.inspect",
    requiredResultFields: [
      "contract.surfaceKind",
      "contract.appViewVariant",
      "contract.nativeFooterSurface",
      "contract.focusPolicy",
      "contract.keyboardPolicy",
      "contract.actionsPolicy",
      "contract.proofPolicy",
      "contract.visualPolicy",
      "contract.dismissPolicy",
      "runtime.activeFooterSurface",
      "runtime.focusedSemanticId",
      "runtime.selectedSemanticId",
      "runtime.capabilities",
      "runtime.missingPrimitives",
    ],
    failClosedWhen: ["surfaceKind mismatches requested surface", "dismissPolicy is missing", "runtime generation is stale"],
  },
  {
    primitive: "devtools.elements.snapshot",
    requiredResultFields: [
      "semanticSurface",
      "semanticSurfaceVersion",
      "nodes[].semanticId",
      "nodes[].role",
      "nodes[].label",
      "nodes[].actions",
      "nodes[].owner",
      "nodes[].bounds",
      "selectedSemanticId",
      "focusedSemanticId",
      "warnings",
    ],
    failClosedWhen: ["semantic ids are missing or duplicated", "focused/selected ids are absent when the surface requires them"],
    implementation: "bun scripts/devtools/elements.ts snapshot",
  },
  {
    primitive: "devtools.layout.measure",
    requiredResultFields: [
      "viewportRect",
      "windowRect",
      "window.rect",
      "viewport.clientHeight",
      "viewport.scrollHeight",
      "viewport.canScrollY",
      "regions",
      "nodes[].bounds",
      "nodes[].clipped",
      "nodes[].overlaps",
      "resizePressure.windowCanGrow",
      "resizePressure.overflowY",
      "resizePressure.clippedNodeCount",
      "resizePressure.overlapCount",
      "resizePressure.pressureScore",
      "pressure.hiddenContentHeight",
      "pressure.footerOverlapCount",
      "pressure.inputOverlapCount",
      "pressure.pressureScore",
    ],
    failClosedWhen: ["region bounds are missing", "target identity is not strict", "layout generation changes mid-measurement"],
    implementation: "bun scripts/devtools/layout.ts measure",
  },
  {
    primitive: "devtools.scroll.inspect",
    requiredResultFields: [
      "scroll.scrollTop",
      "scroll.contentHeight",
      "scroll.viewportHeight",
      "scroll.safeViewportHeight",
      "scroll.maxScrollTop",
      "scroll.canScrollY",
      "scroll.selectedRowVisible",
      "scroll.selectedRowAboveFooter",
      "resizePressure.overflowY",
      "resizePressure.hiddenContentHeight",
      "resizePressure.selectedRowOccluded",
    ],
    failClosedWhen: ["target identity is not strict", "mainListScroll is missing", "selected row visibility is unknown for list surfaces"],
    implementation: "bun scripts/devtools/scroll.ts inspect",
  },
  {
    primitive: "devtools.focus.inspect",
    requiredResultFields: [
      "windowFocused",
      "windowVisible",
      "focusedSemanticId",
      "selectedSemanticId",
      "focusedNode",
      "selectedNode",
      "activeFooter",
      "keyboardOwner.inputOwnership",
      "keyboardOwner.keyboardPolicy",
    ],
    failClosedWhen: ["target identity is not strict", "focusedSemanticId is missing for focusable surfaces", "state/elements disagree about focus owner"],
    implementation: "bun scripts/devtools/focus.ts inspect",
  },
  {
    primitive: "devtools.text.measure",
    requiredResultFields: [
      "textSummary.inputValue",
      "textSummary.inputFingerprint",
      "textSummary.selectedValue",
      "textSummary.selectedFingerprint",
      "textSummary.textNodeCount",
      "rows[].semanticId",
      "rows[].text",
      "rows[].textLength",
      "rows[].fingerprint",
      "footerTexts[].key",
      "footerTexts[].label",
    ],
    failClosedWhen: ["target identity is not strict", "text nodes are missing", "text bounds are required but not available"],
    implementation: "bun scripts/devtools/text.ts measure",
  },
  {
    primitive: "devtools.keyboard.inspect",
    requiredResultFields: [
      "keyboardPolicy",
      "inputOwnership",
      "focusPolicy",
      "activeFooter.owner",
      "activeFooter.activeSurface",
      "activeFooter.nativeFooterHostInstalled",
      "bindings[].source",
      "bindings[].action",
      "bindings[].key",
      "bindings[].label",
      "duplicateKeys",
    ],
    failClosedWhen: ["target identity is not strict", "keyboard bindings are missing", "duplicate keys exist without routing priority"],
    implementation: "bun scripts/devtools/keyboard.ts inspect",
  },
  {
    primitive: "devtools.actions.inspect",
    requiredResultFields: [
      "target.automationId",
      "parentTarget.automationId",
      "proofMode.keepOpen",
      "proofMode.openTarget",
      "popupState.open",
      "popupState.host",
      "routeStack",
      "geometry.popupRect",
      "geometry.parentRect",
      "geometry.anchorRect",
      "geometry.clippingEdges",
      "geometry.layoutPressure",
      "sections.rows",
      "sections.boundsAvailable",
      "actions.rows",
      "shortcutLayout.rows",
      "shortcutLayout.boundsAvailable",
      "missingPrimitives",
    ],
    failClosedWhen: ["ActionsDialog target is missing", "attached popup geometry is unavailable", "row geometry is unavailable", "route stack is unavailable"],
    implementation: "bun scripts/devtools/actions.ts inspect --start --keep-open --open",
  },
  {
    primitive: "devtools.act",
    requiredResultFields: [
      "actionId",
      "actionKind",
      "targetBefore",
      "input",
      "safety",
      "safety.submitIntent",
      "safety.allowSubmitReason",
      "proofIntent",
      "preflightOnly",
      "blockedAction.gateName",
      "blockedAction.nextSafeCommand",
      "submitLifecycle.allowedBy",
      "submitLifecycle.proofIntent",
      "postIntentTargetProof",
      "postIntentTargetProof.expected.expectedSurfaceKind",
      "postIntentTargetProof.receipt.resolvedTarget.strictTargetMatch",
      "expected",
      "targetAfter",
      "visibleResult",
      "result",
    ],
    failClosedWhen: ["targetBefore/targetAfter are missing", "destructive action lacks confirmation", "native escalation is used without safety reason"],
    implementation: "bun scripts/devtools/act.ts set-input|select|key|open-actions",
  },
  {
    primitive: "devtools.compare.redgreen",
    requiredResultFields: [
      "redReceiptIds",
      "greenReceiptIds",
      "samePrimitiveStack",
      "sameUserPath",
      "sameTargetSelector",
      "targetIdentityComparable",
      "assertions",
      "classification",
    ],
    failClosedWhen: ["samePrimitiveStack is false", "target identity is not comparable", "metric names differ between red and green"],
    implementation: "bun scripts/devtools/compare.ts redgreen",
  },
  {
    primitive: "devtools.events.record",
    requiredResultFields: [
      "source.logPath",
      "source.responsesPath",
      "recordedCommand",
      "actionReceipt",
      "outputPolicy.previewBytes",
      "actionOutput.stdoutSummary.bytes",
      "actionOutput.stdoutSummary.omittedBytes",
      "actionOutput.stdoutSummary.fingerprint",
      "actionOutput.stdoutJson.classification",
      "failureSignals.openAi.seen",
      "failureSignals.agent_chat.statusNotAgentChatSeen",
      "externalSession.slug",
      "externalSession.outputLogPath",
      "eventSummary.appLog.byType",
      "eventSummary.responses.byType",
      "events.appLog[].eventType",
      "events.appLog[].correlationId",
      "events.responses[].parsed",
      "warnings",
    ],
    failClosedWhen: ["session logs are unavailable", "recorded command fails", "no events match the action span"],
    implementation: "bun scripts/devtools/events.ts record",
  },
  {
    primitive: "devtools.notes.inspect",
    requiredResultFields: [
      "target.automationId",
      "notesState.panelPresent",
      "notesState.editorPresent",
      "notesState.editorFocused",
      "notesState.editorFingerprint",
      "notesState.activeNoteId",
      "notesState.dirtyState",
      "notesState.selectionRange",
      "notesState.redacted",
      "notesState.editorAnchor.scroll.scrollTop",
      "notesState.editorAnchor.scroll.scrollHeight",
      "notesState.editorAnchor.scroll.clientHeight",
      "notesState.previewAnchor.scrollMetricsAvailable",
      "notesState.layout.editorRegion",
      "notesState.storage.generation",
      "notesState.commandBars.actions.dialog.route.stack",
      "notesState.commandBars.actions.dialog.actions.filteredCount",
      "notesState.commandBars.noteSwitcher.config.searchPosition",
      "notesState.shortcutRegistry.activeScope",
      "notesState.shortcutRegistry.scopes",
      "notesState.focusTransitions.generation",
      "notesState.focusTransitions.entries",
      "shortcutActivation.shortcut",
      "shortcutActivation.channel",
      "shortcutActivation.before",
      "shortcutActivation.after",
      "shortcutActivation.assertions.actionsPanelOpened",
      "runtimeState.notes",
      "coverage.missingRuntimePrimitives",
      "receipts.elements",
      "receipts.focus",
      "receipts.text",
      "receipts.layout",
      "receipts.state",
    ],
    failClosedWhen: ["Notes target is not open", "editor semantic id is missing", "redacted runtime Notes state is unavailable"],
    implementation: "bun scripts/devtools/notes.ts inspect",
  },
  {
    primitive: "devtools.notes.resizeCompare",
    requiredResultFields: [
      "classification",
      "safety.mutationMode",
      "safety.envName",
      "resizeCompare.beforeHeight",
      "resizeCompare.afterGrowHeight",
      "resizeCompare.afterShrinkHeight",
      "resizeCompare.growDeltaPx",
      "resizeCompare.shrinkDeltaPx",
      "resizeCompare.widthStable",
      "resizeCompare.generationOrderValid",
      "resizeCompare.autosize.before.generation",
      "resizeCompare.autosize.afterGrow.generation",
      "resizeCompare.autosize.afterShrink.generation",
      "assertions",
      "missingPrimitives",
      "cleanup.status",
    ],
    failClosedWhen: ["sandbox DB is not active", "target identity is ambiguous", "autosize generation does not advance", "raw note content would be returned"],
    implementation: "bun scripts/devtools/notes.ts resize-compare",
  },
  {
    primitive: "devtools.dictation.inspect",
    requiredResultFields: [
      "passiveSafety.noMicrophoneCaptureRequired",
      "coverage.shortcuts",
      "mediaReceipt.requiredFields",
      "runtimeState.isRecording",
      "runtimeState.phase",
      "runtimeState.target",
      "runtimeState.elapsedMs",
      "runtimeState.lastDelivery.generation",
      "runtimeState.lastDelivery.transcriptFingerprint",
      "deliveryReceiptAvailable",
      "providerResource.uri",
      "providerResource.payloadFingerprint",
      "sourceEvidence.phases",
      "sourceEvidence.targets",
      "sourceEvidence.runtimeReadApis",
      "sourceEvidence.stdin.pushDictationResultVerb",
      "missingPrimitives",
    ],
    failClosedWhen: ["passive runtime dictation state is missing", "provider payload cannot be parsed", "delivery receipts are unavailable"],
    implementation: "bun scripts/devtools/dictation.ts inspect",
  },
  {
    primitive: "devtools.dictation.deliverFixture",
    requiredResultFields: [
      "safety.noMicrophoneCaptureRequired",
      "safety.syntheticTranscriptInjected",
      "safety.transcriptContentReturned",
      "target.requested",
      "target.receiptTarget",
      "target.requestedTargetMatches",
      "delivery.beforeGeneration",
      "delivery.afterGeneration",
      "delivery.advanced",
      "delivery.receipt.transcriptLen",
      "delivery.receipt.transcriptFingerprint",
      "delivery.receipt.insertionRange",
      "delivery.insertionRangeAvailable",
      "delivery.receipt.redacted",
      "delivery.rawTranscriptReturned",
      "missingPrimitives",
    ],
    failClosedWhen: ["delivery generation does not advance", "redacted transcript fingerprint is missing", "insertion range is unavailable for the requested destination", "raw transcript content would be returned"],
    implementation: "bun scripts/devtools/dictation.ts deliver-fixture",
  },
  {
    primitive: "devtools.investigate",
    requiredResultFields: [
      "artifactKind",
      "bugId",
      "intake",
      "environment",
      "hypothesisLog",
      "primitiveStack",
      "red",
      "green",
      "comparison",
      "missingPrimitives",
      "likelyOwners",
      "cleanup",
    ],
    failClosedWhen: ["red classification is missing", "missing primitive lacks required fields", "cleanup state is unknown"],
  },
];

const acceptanceBar = [
  "target identity resolves strictly",
  "surface.inspect returns contract and runtime state",
  "elements.snapshot has stable semantic ids",
  "layout.measure includes regions, overlaps, and resize pressure",
  "scroll/text/focus receipts exist where applicable",
  "act.* can perform at least one user-like operation with pre/post receipts",
  "visual capture has strict target identity and nonblank proof",
  "events record correlates action to state change",
  "compare.redgreen can compare the same primitive stack",
  "investigate can export the artifact",
];

function parseArgs(argv: string[]) {
  return {
    markdown: argv.includes("--markdown"),
  };
}

function report() {
  return {
    schemaVersion: 1,
    tool: "script-kit-devtools.schema",
    generatedAt: new Date().toISOString(),
    source: ".agents/skills/script-kit-devtools/references/devtools-oracle-buildout-plan.md",
    philosophy: "Every DevTools primitive returns a shared fail-closed receipt envelope; screenshots and recipes never replace target-scoped proof.",
    receiptEnvelopeFields,
    classifications,
    targetIdentityFields,
    primitiveSchemas,
    acceptanceBar,
  };
}

function markdown(data: ReturnType<typeof report>) {
  return [
    "# Script Kit DevTools Receipt Schema",
    "",
    data.philosophy,
    "",
    "## Envelope Fields",
    "",
    data.receiptEnvelopeFields.join(", "),
    "",
    "## Classifications",
    "",
    data.classifications.join(", "),
    "",
    "## Primitive Schemas",
    "",
    "| Primitive | Required fields | Fail closed when |",
    "| --- | --- | --- |",
    ...data.primitiveSchemas.map(
      (schema) => `| ${schema.primitive} | ${schema.requiredResultFields.join(", ")} | ${schema.failClosedWhen.join(", ")} |`
    ),
    "",
    "## Acceptance Bar",
    "",
    ...data.acceptanceBar.map((item) => `- ${item}`),
  ].join("\n");
}

const data = report();
if (parseArgs(Bun.argv.slice(2)).markdown) {
  console.log(markdown(data));
} else {
  console.log(JSON.stringify(data, null, 2));
}
