// Auto-generated by scripts/generate-api-tests.ts
// Do not edit manually - regenerate with: bun run scripts/generate-api-tests.ts

import '../../scripts/kit-sdk';

// =============================================================================
// Test Infrastructure
// =============================================================================

interface TestResult {
  test: string;
  status: 'running' | 'pass' | 'fail' | 'skip';
  timestamp: string;
  result?: unknown;
  error?: string;
  duration_ms?: number;
}

function logTest(name: string, status: TestResult['status'], extra?: Partial<TestResult>) {
  const result: TestResult = {
    test: name,
    status,
    timestamp: new Date().toISOString(),
    ...extra
  };
  console.log(JSON.stringify(result));
}

function debug(msg: string) {
  console.error(`[TEST] ${msg}`);
}

async function runTest(name: string, fn: () => Promise<void>) {
  logTest(name, 'running');
  const start = Date.now();
  try {
    await fn();
    logTest(name, 'pass', { duration_ms: Date.now() - start });
  } catch (err) {
    logTest(name, 'fail', { error: String(err), duration_ms: Date.now() - start });
  }
}

function skipTest(name: string, reason: string) {
  logTest(name, 'skip', { error: reason });
}

// =============================================================================
// Tests
// =============================================================================

debug('test-storage-apis.ts starting...');

// -----------------------------------------------------------------------------
// Path utilities tests (pure functions)
// -----------------------------------------------------------------------------

await runTest('home-path', async () => {
  const result = home();
  if (typeof result !== 'string' || !result.includes('/')) {
    throw new Error(`Expected valid home path, got: ${result}`);
  }
  debug(`home(): ${result}`);
});

await runTest('home-with-subpath', async () => {
  const result = home('Documents');
  if (!result.includes('Documents')) {
    throw new Error(`Expected path with Documents, got: ${result}`);
  }
});

await runTest('kenvPath-basic', async () => {
  const result = kenvPath();
  if (!result.includes('.kenv')) {
    throw new Error(`Expected .kenv in path, got: ${result}`);
  }
});

await runTest('kitPath-basic', async () => {
  const result = kitPath();
  // kitPath() now returns ~/.kenv paths (deprecated in favor of kenvPath())
  if (!result.includes('.kenv')) {
    throw new Error(`Expected .kenv in path, got: ${result}`);
  }
});

await runTest('tmpPath-basic', async () => {
  const result = tmpPath();
  if (typeof result !== 'string') {
    throw new Error(`Expected string path, got: ${typeof result}`);
  }
});

// -----------------------------------------------------------------------------
// File check tests
// -----------------------------------------------------------------------------

await runTest('isFile-true', async () => {
  const result = await isFile('/etc/hosts');
  if (result !== true) {
    throw new Error(`Expected true for /etc/hosts, got: ${result}`);
  }
});

await runTest('isFile-false', async () => {
  const result = await isFile('/nonexistent-file-12345');
  if (result !== false) {
    throw new Error(`Expected false for nonexistent file, got: ${result}`);
  }
});

await runTest('isDir-true', async () => {
  const result = await isDir('/tmp');
  if (result !== true) {
    throw new Error(`Expected true for /tmp, got: ${result}`);
  }
});

await runTest('isDir-false', async () => {
  const result = await isDir('/nonexistent-dir-12345');
  if (result !== false) {
    throw new Error(`Expected false for nonexistent dir, got: ${result}`);
  }
});

// -----------------------------------------------------------------------------
// uuid() tests
// -----------------------------------------------------------------------------

await runTest('uuid-basic', async () => {
  const result = uuid();
  if (typeof result !== 'string' || result.length < 32) {
    throw new Error(`Expected UUID string, got: ${result}`);
  }
  // Basic UUID format check
  if (!/^[0-9a-f-]{36}$/i.test(result)) {
    throw new Error(`Invalid UUID format: ${result}`);
  }
});

// -----------------------------------------------------------------------------
// store tests
// -----------------------------------------------------------------------------

await runTest('store-set-get', async () => {
  const testKey = 'test-key-' + Date.now();
  const testValue = 'test-value-' + Date.now();
  
  await store.set(testKey, testValue);
  const result = await store.get(testKey);
  
  if (result !== testValue) {
    throw new Error(`Store roundtrip failed: expected "${testValue}", got "${result}"`);
  }
});

// -----------------------------------------------------------------------------
// db() tests
// -----------------------------------------------------------------------------

await runTest('db-basic', async () => {
  const database = await db({ items: [] });
  if (!database || database.data === undefined) {
    throw new Error('Expected database object with data property');
  }
});

debug('test-storage-apis.ts completed!');
