/* Demo script: 02-search-filter — "type once to search every result source". */
SKDemo.define({
  id: "02-search-filter",
  initialHoldMs: 900,
  idleResetMs: 8000,
  loopDelayMs: 1200,
  controls: {
    input: {
      target: '[data-demo-key="query"]',
      maxLength: 40,
      items: '[data-demo-role="result"]',
      matchAttribute: "data-demo-match",
    },
    list: {
      items: '[data-demo-role="result"]',
      state: { type: "attribute", name: "data-state", selected: "selected", hover: "hover" },
    },
  },
  states: {
    unfiltered: [
      { op: "setState", target: '[data-demo-key="list"]', attribute: "data-demo-nomatch", value: "1" },
      { op: "setState", target: '[data-demo-key="emoji-picker"]', attribute: "data-state", value: null },
      { op: "setText", target: '[data-demo-key="query"]', text: "" },
      { op: "show", target: "[data-demo-only]" },
      { op: "moveSelection", group: '[data-demo-role="result"]', to: '[data-demo-key="theme-designer"]' },
    ],
    clipFinal: [
      { op: "setState", target: '[data-demo-key="list"]', attribute: "data-demo-nomatch", value: null },
      { op: "hide", target: "[data-demo-only]" },
      { op: "moveSelection", group: '[data-demo-role="result"]', to: '[data-demo-key="clipboard-history"]' },
      { op: "setState", target: '[data-demo-key="emoji-picker"]', attribute: "data-state", value: "hover" },
      { op: "setText", target: '[data-demo-key="primary-label"]', text: "Open Clipboard History" },
    ],
  },
  steps: [
    { id: "intro", op: "caption", text: "Type once to search every result source.", holdMs: 1100 },
    { id: "unfiltered", op: "applyState", name: "unfiltered" },
    { op: "pause", ms: 900 },
    {
      id: "type-clip",
      op: "typeInto",
      target: '[data-demo-key="query"]',
      text: "clip",
      clear: true,
      perCharacterMs: 75,
      filter: { items: '[data-demo-role="result"]', matchAttribute: "data-demo-match" },
    },
    { id: "clip-final", op: "applyState", name: "clipFinal" },
    { op: "pause", ms: 650 },
    {
      id: "arrow-down",
      op: "keypress",
      keys: ["↓"],
      holdMs: 250,
    },
    { op: "moveSelection", group: '[data-demo-role="result"]', to: '[data-demo-key="clipboard"]', holdMs: 200 },
    { op: "setText", target: '[data-demo-key="primary-label"]', text: "Open Clipboard" },
    { op: "pause", ms: 650 },
    { id: "arrow-up", op: "keypress", keys: ["↑"], holdMs: 250 },
    { op: "moveSelection", group: '[data-demo-role="result"]', to: '[data-demo-key="clipboard-history"]', holdMs: 200 },
    { op: "setText", target: '[data-demo-key="primary-label"]', text: "Open Clipboard History" },
    { op: "pause", ms: 650 },
    {
      id: "actions",
      op: "keypress",
      keys: ["⌘", "K"],
      activate: '[data-demo-key="actions"]',
      holdMs: 700,
    },
    { op: "loop", delayMs: 1200 },
  ],
});
