//! Lucide icon name mapping

/// Parse a string into a gpui_component::IconName
///
/// Supports kebab-case and common aliases
pub fn lucide_from_str(name: &str) -> Option<gpui_component::IconName> {
    let name = name.to_lowercase();

    match name.as_str() {
        // Exact matches (kebab-case)
        "a-large-small" => Some(gpui_component::IconName::ALargeSmall),
        "arrow-down" => Some(gpui_component::IconName::ArrowDown),
        "arrow-left" => Some(gpui_component::IconName::ArrowLeft),
        "arrow-right" => Some(gpui_component::IconName::ArrowRight),
        "arrow-up" => Some(gpui_component::IconName::ArrowUp),
        "asterisk" => Some(gpui_component::IconName::Asterisk),
        "battery" => Some(gpui_component::IconName::Battery),
        "battery-charging" => Some(gpui_component::IconName::BatteryCharging),
        "battery-full" => Some(gpui_component::IconName::BatteryFull),
        "battery-low" => Some(gpui_component::IconName::BatteryLow),
        "battery-medium" => Some(gpui_component::IconName::BatteryMedium),
        "battery-warning" => Some(gpui_component::IconName::BatteryWarning),
        "bell" => Some(gpui_component::IconName::Bell),
        "book-open" => Some(gpui_component::IconName::BookOpen),
        "bot" => Some(gpui_component::IconName::Bot),
        "building-2" => Some(gpui_component::IconName::Building2),
        "calendar" => Some(gpui_component::IconName::Calendar),
        "case-sensitive" => Some(gpui_component::IconName::CaseSensitive),
        "chart-pie" => Some(gpui_component::IconName::ChartPie),
        "check" => Some(gpui_component::IconName::Check),
        "chevron-down" => Some(gpui_component::IconName::ChevronDown),
        "chevron-left" => Some(gpui_component::IconName::ChevronLeft),
        "chevron-right" => Some(gpui_component::IconName::ChevronRight),
        "chevrons-up-down" => Some(gpui_component::IconName::ChevronsUpDown),
        "chevron-up" => Some(gpui_component::IconName::ChevronUp),
        "circle-check" => Some(gpui_component::IconName::CircleCheck),
        "circle-user" => Some(gpui_component::IconName::CircleUser),
        "circle-x" => Some(gpui_component::IconName::CircleX),
        "close" => Some(gpui_component::IconName::Close),
        "copy" => Some(gpui_component::IconName::Copy),
        "cpu" => Some(gpui_component::IconName::Cpu),
        "dash" => Some(gpui_component::IconName::Dash),
        "delete" => Some(gpui_component::IconName::Delete),
        "ellipsis" => Some(gpui_component::IconName::Ellipsis),
        "ellipsis-vertical" => Some(gpui_component::IconName::EllipsisVertical),
        "external-link" => Some(gpui_component::IconName::ExternalLink),
        "eye" => Some(gpui_component::IconName::Eye),
        "eye-off" => Some(gpui_component::IconName::EyeOff),
        "file" => Some(gpui_component::IconName::File),
        "folder" => Some(gpui_component::IconName::Folder),
        "folder-closed" => Some(gpui_component::IconName::FolderClosed),
        "folder-open" => Some(gpui_component::IconName::FolderOpen),
        "frame" => Some(gpui_component::IconName::Frame),
        "gallery-vertical-end" => Some(gpui_component::IconName::GalleryVerticalEnd),
        "github" => Some(gpui_component::IconName::GitHub),
        "globe" => Some(gpui_component::IconName::Globe),
        "hard-drive" => Some(gpui_component::IconName::HardDrive),
        "heart" => Some(gpui_component::IconName::Heart),
        "heart-off" => Some(gpui_component::IconName::HeartOff),
        "inbox" => Some(gpui_component::IconName::Inbox),
        "info" => Some(gpui_component::IconName::Info),
        "inspector" => Some(gpui_component::IconName::Inspector),
        "layout-dashboard" => Some(gpui_component::IconName::LayoutDashboard),
        "loader" => Some(gpui_component::IconName::Loader),
        "loader-circle" => Some(gpui_component::IconName::LoaderCircle),
        "map" => Some(gpui_component::IconName::Map),
        "maximize" => Some(gpui_component::IconName::Maximize),
        "memory-stick" => Some(gpui_component::IconName::MemoryStick),
        "menu" => Some(gpui_component::IconName::Menu),
        "minimize" => Some(gpui_component::IconName::Minimize),
        "minus" => Some(gpui_component::IconName::Minus),
        "moon" => Some(gpui_component::IconName::Moon),
        "network" => Some(gpui_component::IconName::Network),
        "palette" => Some(gpui_component::IconName::Palette),
        "panel-bottom" => Some(gpui_component::IconName::PanelBottom),
        "panel-bottom-open" => Some(gpui_component::IconName::PanelBottomOpen),
        "panel-left" => Some(gpui_component::IconName::PanelLeft),
        "panel-left-close" => Some(gpui_component::IconName::PanelLeftClose),
        "panel-left-open" => Some(gpui_component::IconName::PanelLeftOpen),
        "panel-right" => Some(gpui_component::IconName::PanelRight),
        "panel-right-close" => Some(gpui_component::IconName::PanelRightClose),
        "panel-right-open" => Some(gpui_component::IconName::PanelRightOpen),
        "plus" => Some(gpui_component::IconName::Plus),
        "redo" => Some(gpui_component::IconName::Redo),
        "redo-2" => Some(gpui_component::IconName::Redo2),
        "replace" => Some(gpui_component::IconName::Replace),
        "resize-corner" => Some(gpui_component::IconName::ResizeCorner),
        "search" => Some(gpui_component::IconName::Search),
        "settings" => Some(gpui_component::IconName::Settings),
        "settings-2" => Some(gpui_component::IconName::Settings2),
        "sort-ascending" => Some(gpui_component::IconName::SortAscending),
        "sort-descending" => Some(gpui_component::IconName::SortDescending),
        "square-terminal" => Some(gpui_component::IconName::SquareTerminal),
        "star" => Some(gpui_component::IconName::Star),
        "star-fill" => Some(gpui_component::IconName::StarFill),
        "star-off" => Some(gpui_component::IconName::StarOff),
        "sun" => Some(gpui_component::IconName::Sun),
        "thumbs-down" => Some(gpui_component::IconName::ThumbsDown),
        "thumbs-up" => Some(gpui_component::IconName::ThumbsUp),
        "triangle-alert" => Some(gpui_component::IconName::TriangleAlert),
        "undo" => Some(gpui_component::IconName::Undo),
        "undo-2" => Some(gpui_component::IconName::Undo2),
        "user" => Some(gpui_component::IconName::User),
        "window-close" => Some(gpui_component::IconName::WindowClose),
        "window-maximize" => Some(gpui_component::IconName::WindowMaximize),
        "window-minimize" => Some(gpui_component::IconName::WindowMinimize),
        "window-restore" => Some(gpui_component::IconName::WindowRestore),

        // Common aliases
        "x" => Some(gpui_component::IconName::Close),
        "trash" => Some(gpui_component::IconName::Delete),
        "cog" | "gear" => Some(gpui_component::IconName::Settings),
        "magnifying-glass" | "find" => Some(gpui_component::IconName::Search),
        "add" => Some(gpui_component::IconName::Plus),
        "remove" => Some(gpui_component::IconName::Minus),
        "checkmark" | "tick" => Some(gpui_component::IconName::Check),
        "warning" | "alert" => Some(gpui_component::IconName::TriangleAlert),
        "terminal" => Some(gpui_component::IconName::SquareTerminal),
        "document" | "doc" => Some(gpui_component::IconName::File),
        "directory" => Some(gpui_component::IconName::Folder),
        "left" => Some(gpui_component::IconName::ArrowLeft),
        "right" => Some(gpui_component::IconName::ArrowRight),
        "up" => Some(gpui_component::IconName::ArrowUp),
        "down" => Some(gpui_component::IconName::ArrowDown),

        _ => None,
    }
}
